//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCIntegratie.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Dagen.
        /// </summary>
        public static string aantalDagen {
            get {
                return ResourceManager.GetString("aantalDagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Thema&apos;s.
        /// </summary>
        public static string aantalThema {
            get {
                return ResourceManager.GetString("aantalThema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Weken.
        /// </summary>
        public static string aantalWeken {
            get {
                return ResourceManager.GetString("aantalWeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuratie.
        /// </summary>
        public static string Configuratie {
            get {
                return ResourceManager.GetString("Configuratie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan niet meer dan 5 personen toevoegen.
        /// </summary>
        public static string err5personen {
            get {
                return ResourceManager.GetString("err5personen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolutie van het aantal tweets.
        /// </summary>
        public static string evTweet {
            get {
                return ResourceManager.GetString("evTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoe gebruik je onze site?.
        /// </summary>
        public static string gebruik {
            get {
                return ResourceManager.GetString("gebruik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string gemeente {
            get {
                return ResourceManager.GetString("gemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string geslacht {
            get {
                return ResourceManager.GetString("geslacht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafiek opslaan.
        /// </summary>
        public static string grafiekOpslaan {
            get {
                return ResourceManager.GetString("grafiekOpslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafiek Titel.
        /// </summary>
        public static string grafTit {
            get {
                return ResourceManager.GetString("grafTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onze groepsleden zijn: Evelien Hullebroeck, Brent Vermolen, Jonas Hofmans, Nathan Van Hof, Jos Hauqiuer en Daan Schokkaert..
        /// </summary>
        public static string groepsleden {
            get {
                return ResourceManager.GetString("groepsleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onze groepsnaam is: &quot;Bit By Bit&quot;..
        /// </summary>
        public static string groepsnaam {
            get {
                return ResourceManager.GetString("groepsnaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startpagina.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij zijn een groep studenten uit de richting Toegepaste Informatice aan de Karel De Grote Hogeschool in antwerpen..
        /// </summary>
        public static string info_groep {
            get {
                return ResourceManager.GetString("info_groep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies.
        /// </summary>
        public static string kies {
            get {
                return ResourceManager.GetString("kies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kruising.
        /// </summary>
        public static string kruising {
            get {
                return ResourceManager.GetString("kruising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kruis met.
        /// </summary>
        public static string kruisMet {
            get {
                return ResourceManager.GetString("kruisMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd.
        /// </summary>
        public static string leeftijd {
            get {
                return ResourceManager.GetString("leeftijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ga terug naar boven.
        /// </summary>
        public static string naarBoven {
            get {
                return ResourceManager.GetString("naarBoven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe Grafiek.
        /// </summary>
        public static string NieuweGraf {
            get {
                return ResourceManager.GetString("NieuweGraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opleiding.
        /// </summary>
        public static string opleiding {
            get {
                return ResourceManager.GetString("opleiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtags over.
        /// </summary>
        public static string overHast {
            get {
                return ResourceManager.GetString("overHast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions over.
        /// </summary>
        public static string overMent {
            get {
                return ResourceManager.GetString("overMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over ons.
        /// </summary>
        public static string overons {
            get {
                return ResourceManager.GetString("overons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets over.
        /// </summary>
        public static string overTweet {
            get {
                return ResourceManager.GetString("overTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht.
        /// </summary>
        public static string overzicht {
            get {
                return ResourceManager.GetString("overzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht van.
        /// </summary>
        public static string overzichtvan {
            get {
                return ResourceManager.GetString("overzichtvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per Dag.
        /// </summary>
        public static string perDag {
            get {
                return ResourceManager.GetString("perDag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijkheid.
        /// </summary>
        public static string persoonlijkheid {
            get {
                return ResourceManager.GetString("persoonlijkheid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per Week.
        /// </summary>
        public static string perWeek {
            get {
                return ResourceManager.GetString("perWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politieker.
        /// </summary>
        public static string politieker {
            get {
                return ResourceManager.GetString("politieker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politiekers.
        /// </summary>
        public static string politiekers {
            get {
                return ResourceManager.GetString("politiekers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Registreren {
            get {
                return ResourceManager.GetString("Registreren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollen.
        /// </summary>
        public static string Rollen {
            get {
                return ResourceManager.GetString("Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string taal {
            get {
                return ResourceManager.GetString("taal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema.
        /// </summary>
        public static string thema {
            get {
                return ResourceManager.GetString("thema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema&apos;s.
        /// </summary>
        public static string themas {
            get {
                return ResourceManager.GetString("themas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string toevoegen {
            get {
                return ResourceManager.GetString("toevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon Preview.
        /// </summary>
        public static string toonpreview {
            get {
                return ResourceManager.GetString("toonpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string trend {
            get {
                return ResourceManager.GetString("trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig taal.
        /// </summary>
        public static string veranderTaal {
            get {
                return ResourceManager.GetString("veranderTaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verhalen.
        /// </summary>
        public static string verhalen {
            get {
                return ResourceManager.GetString("verhalen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg toe.
        /// </summary>
        public static string voegtoe {
            get {
                return ResourceManager.GetString("voegtoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Hashtags.
        /// </summary>
        public static string vrgkAantalHast {
            get {
                return ResourceManager.GetString("vrgkAantalHast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Mentions.
        /// </summary>
        public static string vrgkAantalMent {
            get {
                return ResourceManager.GetString("vrgkAantalMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal Tweets.
        /// </summary>
        public static string vrgkAantalTweet {
            get {
                return ResourceManager.GetString("vrgkAantalTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat.
        /// </summary>
        public static string wat {
            get {
                return ResourceManager.GetString("wat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woorden.
        /// </summary>
        public static string woorden {
            get {
                return ResourceManager.GetString("woorden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken...
        /// </summary>
        public static string Zoeken {
            get {
                return ResourceManager.GetString("Zoeken", resourceCulture);
            }
        }
    }
}
